### PR TITLE
fix(macos_m1): Added PATH setting to run aws commands

### PR DESCRIPTION
**Pull request by jakub-kocka**
Added AWS into PATH where it is needed to upload release asset.

[The jobs were failing](https://github.com/espressif/idf-python-wheels/actions/runs/6679996610)

[Successful job with this change](https://github.com/espressif/idf-python-wheels/actions/runs/6690273909/job/18175271690)

### CODE REVIEW

**Comment by jakub-kocka** [comment]
It is additional fix to the https://github.com/espressif/idf-python-wheels/pull/17 PR.

**Review by dobairoland — APPROVED** [review]
LGTM

**Comment by fhrbata** [comment]
@jakub-kocka , Just out of curiosity, do we know what has changed since 71a219316f72, because it seems that the workflow was passing then. Thank you

**Review by tomassebestik — APPROVED** [review]
LGTM

**Comment by jakub-kocka** [comment]
> @jakub-kocka , Just out of curiosity, do we know what has changed since [71a2193](https://github.com/espressif/idf-python-wheels/commit/71a219316f728ea73e894a59fd6cc86daf0c16e2), because it seems that the workflow was passing then. Thank you

@fhrbata it could be that the self hosted runner with M1 was reinstalled completely (a week ago) and probably GH actions logic change. The AWS is installed in the runner, but not in the workflow PATH and it is not remembered between steps of the job.

I haven't done a further investigation of GH action logic nor used 
 the environmental variable because I have already started the rewriting of the wheel builds, so I will try to improve it as the new version comes to that point.

**Pull request merged**
