### PR TITLE
Delete .github/workflows/build-cmake-linux-armv7.yml (IDFGH-14061)

### PR DESCRIPTION
**Pull request by macko1**
## Description

We are moving this pipeline to our private repository outside of GH.

## Related
No related public issue.

### CODE REVIEW

**Comment by tomassebestik** [comment]
@macko1 Pls fix danger issues first

**Comment by tomassebestik** [comment]
@jakub-kocka Without this workflow removed (moved to internal @Gitlab `idf/cmake-arm-v7` project) - do we still AWS credentials action secrets in the repo?

**Comment by tomassebestik** [comment]
> @jakub-kocka ~~With this workflow removed (moved to internal @GitLab `idf/cmake-arm-v7` project) - do we still AWS credentials action secrets in the repo?~~

I can see it is also used for upload python wheels, so needs to stay. Pls ignore this comment.

**Review by jakub-kocka — APPROVED** [review]
LGTM

**Review by dobairoland — APPROVED** [review]
LGTM

**Pull request merged**
