### PR TITLE
allow to build wheels for selected packages only

### PR DESCRIPTION
**Pull request by fhrbata**
Currently packages are built based on the requirements files only. This PR adds a new manual workflow, which allows to build specific packages with requirement specifiers manually for selected operating systems/architectures.

### CODE REVIEW

**Comment by fhrbata** [comment]
Hi Juraj(@JurajSadel)/Roland (@dobairoland),

this is the first version and hopefully I haven't missed anything crucial. It would be great if you could take a look.

Thank you!

**Comment by dobairoland** [comment]
LGTM. Thank you @fhrbata!

**Review by JurajSadel — CHANGES_REQUESTED** [review]
LGTM, thank you @fhrbata! 
Before we merge this, we have to address passing GitHub secrets to the second workflow - I left a comment about it.

**Comment by fhrbata** [comment]
@JurajSadel  `secrets: inherit` added, Could you PTAL? Thank you!

**Comment by JurajSadel** [comment]
@fhrbata Thank you for making that changes! One more question from my side, what is the motivation behind the `upload` argument?

**Comment by fhrbata** [comment]
> @fhrbata Thank you for making that changes! One more question from my side, what is the motivation behind the `upload` argument?

@JurajSadel I used it just for testing to avoid running the upload/index steps, which would fail anyways. If it all works we can remove it. Also I guess it should be enabled by default in the ad hoc wheels workflow. I have no strong opinion on this, so just let me know what you prefer and I will adjust the PR.

Thank you

**Comment by JurajSadel** [comment]
@fhrbata I agree with you, let's remove it :)

**Comment by fhrbata** [comment]
> @fhrbata I agree with you, let's remove it :)
@JurajSadel  again thank you for looking into this. The upload var should be removed now.

**Review by JurajSadel — APPROVED** [review]
@fhrbata LGTM, thank you very much for working on this!

**Pull request merged**
